version: '2'
services:

  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  default:
    external:
      name: myapp
